spring:
  application:
    name: cloud-server-2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/    
ribbon:
  eureka:
    enabled: true      #serviceList 交给eureka管理。ribbon就不要配置ServiceList了
    
            
# feign开启hystrix熔断服务
feign:
  hystrix:
    enabled: true

server:
  port: 83