spring:
  application:
    name: cloud-gateway-3
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/



zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cloud-server-1
    api-b:
      path: /api-b/**
      serviceId: cloud-server-2

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000   #zuul路由熔断时间
ribbon:
  ConnectTimeout: 3000 #zuul路由连接时间
  ReadTimeout: 60000  #zuul路由响应时间时间
